### ISSUE TITLE
I made a theme

### ISSUE THREAD

**Issue by akash-vartak** [Brackets-Themes/brackets-themes.github.io#26]
I have made a theme and i would like to contribute to the project by supplying my theme for use in the Brackets editor. Do I have to submit anything to do that...basically I want my theme to feature in the 'Available themes' section in Extensions Manager.
Please help. Thanks.

**Comment by wormeyman** [comment]
I assume you are talking about https://github.com/akash-vartak/Simply-Unique? All you need to do is zip it up and submit it:

https://github.com/adobe/brackets/wiki/Creating-Themes#publishing-your-theme

Edit: i'll send you a pull request with some small changes.

**Comment by akash-vartak** [comment]
Ohk Sir Thanks....
I'll get back to you as soon I do that above mentioned stuff
