### ISSUE TITLE
updated site... changed layout

### ISSUE THREAD

**Issue by mackenza** [Brackets-Themes/brackets-themes.github.io#4]
I added the logo and the latest themes to the readme.md.  This is used as the source for generating the site via the auto site generator.  

I changed the layout to something more neutral to highlight the themes, not the site.  Let me know if it's ok.

One of the issues with using auto layouts is that you don't tightly control the site css or html template.  So, the logo looks ok but should probably be tweaked to float or align somewhere else.  Feel free to edit the template files to make this work better and I promise not to overwrite your changes in the future with the generator ;)

**Comment by wormeyman** [comment]
I also noticed that the logo has a white background on the png instead of transparent, also the emoji have a lot of padding and margins on them.
- [ ] Transparent PNG
- [ ] Emoji padding/margins
